[build]
builder = "NIXPACKS"
buildCommand = "npm run build:railway"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
FONTCONFIG_PATH = "./fonts"
CANVAS_FONT_PATH = "./fonts"
